---
- hosts: host1
  become: yes
  tasks:
    - name: Checking the contents of folder
      command: "ls /ansible"
      register: contents

    - name: Display the message
      debug:
        msg: "Directory is empty"
      when: contents.stdout == ""
