---
- name: checking shell commands
  hosts: host1
  tasks: 
    - name: checking date in slave machine 
      shell: 
        "date"
      register: datecmd
      tags: datecmd
    - debug: msg="{{ datecmd.stdout }}"    
