---
- name: installing lighthttpd 
  hosts: host1
  become: yes
  tasks: 
    - name: installng lighthttpd
      apt:
        name: lighttpd
        state: latest
    - name: start server
      service:
        name: lighttpd
        state: started    
